### ISSUE TITLE
Add support for python3

### ISSUE THREAD

**Issue by je-vv** [johncheetham/samuel#1]
It's been a while since there's no new release, latest one being [0.1.8](https://github.com/johncheetham/samuel/releases/tag/SAMUEL_0_1_8), which depends on python2, and it's from 2009 according to [samuel project](http://johncheetham.com/projects/samuel), 9+ years old.

In the same [samuel project](http://johncheetham.com/projects/samuel) indicates that git already includes support for gtk3, which is nice, but that new support never got released, besides it says nothing about python3, and python2 is soon to become unsupported.

**Comment by johncheetham** [comment]
I created a new development branch. I've ported it to python3 but it needs work. I'll work on it and hopefully release a new version.

**Comment by johncheetham** [comment]
A new version 0.1.9 has been released which uses python3.
