### ISSUE TITLE
Try my app

### ISSUE THREAD

**Issue by VietTho1989** [johncheetham/samuel#2]
Hi, I use your draughts in my chess app: https://youtu.be/RNfptp2fFrI?t=18520, please try:
+ Android: https://play.google.com/store/apps/details?id=com.doanviettho.hundredgamesmaster
+ Windows: https://github.com/VietTho1989/TurnBasedGame/releases/download/1.1/WindowsBuild.rar
+ Source code: https://github.com/VietTho1989/TurnBasedGame
   Thanks.

**Comment by johncheetham** [comment]
Thanks for sharing this. I tried a few games and it all worked very nicely. Great work.
