### ISSUE TITLE
International Checkerboard

### ISSUE THREAD

**Issue by ThierryHFR** [johncheetham/samuel#5]
Thank you for this nice project.
I could easily adapt the checkerboard to make it dynamic, I would like to be able to use it for games of 8, 10 and 12 squares per line.
Italian => 8 squares.
French and International => 10 squares.
German => 12 squares.
Do you think it would be easy to transform your AI to, to support these different checkers.
I would like to add a menu: Country.

**Comment by johncheetham** [comment]
Changing it to play other types of game such as international would be good. I don't think changing the AI would be easy though. I didn't write the AI code and don't have the knowledge to change it. The AI code comes from the guicheckers project and there is some programming information about it on the guicheckers homepage. I know it makes use of bitboards.  

Feel free to add new menus etc.

**Comment by johncheetham** [comment]
Closing this since project is no longer maintained and has been archived.
